name: flutter_quick_package
description: 网络层，基于映射能力提供模块分离能力
version: 0.0.1
homepage: "https://github.com/vsguji/flutter_quick_package.git"
publish_to: "https://github.com/vsguji/flutter_quick_package.git"

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0 # 网络请求   
  dio_cache_interceptor: ^3.2.7 # 设置网络缓存
  package_info: ^2.0.2 # 应用信息
  shared_preferences: ^2.0.6 # 应用配置
  reflectable: ^3.0.1 # 反射
  build_runner: ^2.1.2
  built_value_generator: ^8.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
